name: CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/release'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm i --legacy-peer-deps

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with: 
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu/blog
          remote_host: 15.236.229.157
          remote_user: ubuntu
          remote_key: "${{ secrets.BLOG }}"

